---
- debug:
    msg: "SWPM: {{ sap_swpm_sapinst_path }}\n HANA system PW: {{sap_swpm_db_system_password}} \n SWPM master PW {{sap_swpm_master_password }} \n 
        sap_install_media_detect_source_directory: {{ sap_install_media_detect_source_directory}} \n CAtalog ID: {{ sap_swpm_product_catalog_id }} \n SAP APP SID: {{sap_swpm_sid}}\n ASCS {{ sap_swpm_ascs_instance_nr }} \n 
        HANA Host {{ sap_swpm_db_host}}\ \n pas instance number {{ sap_swpm_pas_instance_nr}} \n SAP HANA SID {{ sap_hana_install_sid }} \n SAP HANA Nr {{ sap_swpm_db_instance_nr }} \n "
- name: SAP SWPM - run pre_install tasks
  ansible.builtin.import_tasks: pre_install.yml
  tags:
    - sap_swpm_pre_install
    - sap_swpm_install
- debug:
    msg: "SWPM: {{ sap_swpm_sapinst_path }}\n HANA system PW: {{sap_swpm_db_system_password}} \n SWPM master PW {{sap_swpm_master_password }} \n 
        sap_install_media_detect_source_directory: {{ sap_install_media_detect_source_directory}} \n CAtalog ID: {{ sap_swpm_product_catalog_id }} \n SAP APP SID: {{sap_swpm_sid}}\n ASCS {{ sap_swpm_ascs_instance_nr }} \n 
        HANA Host {{ sap_swpm_db_host}}\ \n pas instance number {{ sap_swpm_pas_instance_nr}} \n SAP HANA SID {{ sap_hana_install_sid }} \n SAP HANA Nr {{ sap_swpm_db_instance_nr }} \n "
- name: SAP SWPM - run swpm
  ansible.builtin.import_tasks: swpm.yml
  tags:
    - sap_swpm_install

- name: SAP SWPM - run postinstall task
  ansible.builtin.import_tasks: post_install.yml
