- name: SAP SWPM Pre Install - Get HANA hostname from Landscape
  when: (sap_swpm_db_host | type_debug == 'NoneType') or
        (sap_swpm_db_host | length == 0)
  block:
    - set_fact: SAP SWPM Pre Install - Get SAP HANA IP from morpheus environment
        sap_hana_ip: "{{ morpheus['evars']['SAP_HANA_IP'] }}"
    - name: SAP SWPM Pre Install - Detect SAP HANA hostname from /etc/hosts
      shell:  grep {{sap_hana_ip }} /etc/hosts | cut -d ' ' -f 3
      register: result
    - set_fact: SAP SWPM Pre Install - Set SAP HANA DB host {{ result.stdout }}
        sap_swpm_db_host : "{{ result.stdout }}"
