---
- debug:
    msg: "SWPM: {{ sap_swpm_sapinst_path }}\n HANA system PW: {{sap_swpm_db_system_password}} \n SWPM master PW {{sap_swpm_master_password }} \n 
        sap_install_media_detect_source_directory: {{ sap_install_media_detect_source_directory}} \n CAtalog ID: {{ sap_swpm_product_catalog_id }} \n SAP APP SID: {{sap_swpm_sid}}\n ASCS {{ sap_swpm_ascs_instance_nr }} \n 
        HANA Host {{ sap_swpm_db_host}}\ \n pas instance number {{ sap_swpm_pas_instance_nr}} \n SAP HANA SID {{ sap_hana_install_sid }} \n SAP HANA Nr {{ sap_swpm_db_instance_nr }} \n "
# Create temporary directory
- name: SAP SWPM Pre Install - Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: swpmconfig
  register: sap_swpm_tmpdir
  tags:
    - sap_swpm_generate_inifile
    - sap_swpm_sapinst_commandline

# Copy password file to the same location as inifile.params
- name: SAP SWPM Pre Install - Copy password file to the same location as inifile.params
  ansible.builtin.copy:
    src: "{{ sap_swpm_password_file_path }}/instkey.pkey"
    dest: "{{ sap_swpm_tmpdir.path }}/instkey.pkey"
    remote_src: yes
    mode: '0640'
  when: sap_swpm_use_password_file == "y"
  tags: sap_swpm_generate_inifile
- debug:
    msg: "SWPM ansible role mode : {{ sap_swpm_ansible_role_mode }} "
# Run SWPM inifile generation based on ansible role mode
- name: SAP SWPM Pre Install - generate swpm inifile
  ansible.builtin.include_tasks: "swpm_inifile_generate_{{ sap_swpm_ansible_role_mode }}.yml"
  tags: sap_swpm_generate_inifile
- debug:
    msg: "SWPM: {{ sap_swpm_sapinst_path }}\n HANA system PW: {{sap_swpm_db_system_password}} \n SWPM master PW {{sap_swpm_master_password }} \n 
        sap_install_media_detect_source_directory: {{ sap_install_media_detect_source_directory}} \n CAtalog ID: {{ sap_swpm_product_catalog_id }} \n SAP APP SID: {{sap_swpm_sid}}\n ASCS {{ sap_swpm_ascs_instance_nr }} \n 
        HANA Host {{ sap_swpm_db_host}}\ \n pas instance number {{ sap_swpm_pas_instance_nr}} \n SAP HANA SID {{ sap_hana_install_sid }} \n SAP HANA Nr {{ sap_swpm_db_instance_nr }} \n "

- name: SAP SWPM Pre Install - Display the location of file 'inifile.params'
  ansible.builtin.debug:
    msg: "{{ sap_swpm_tmpdir.path }}/inifile.params"
  tags: sap_swpm_generate_inifile

# Set fact for SWPM path
#- name: SAP SWPM Pre Install - Set fact for SWPM path
#  ansible.builtin.set_fact:
#    sap_swpm_sapinst_path: "{{ sap_swpm_swpm_path }}/sap_swpm_extracted"

    #- name: SAP SWPM Pre Install - Ensure directory '{{ sap_swpm_sapinst_path }}' exists
    #  ansible.builtin.file:
    #    path: "{{ sap_swpm_sapinst_path }}"
    #    state: directory
    #    mode: '0755'

# Extract SWPM
#- name: SAP SWPM Pre Install - Extract SWPM
#  ansible.builtin.command: >-
#    {{ sap_swpm_sapcar_path }}/{{ sap_swpm_sapcar_file_name }} \
#    -xvf {{ sap_swpm_swpm_path }}/{{ sap_swpm_swpm_sar_file_name }} \
#    -manifest SIGNATURE.SMF
#  register: sap_swpm_extractswpm
#  args:
#    chdir: "{{ sap_swpm_sapinst_path }}"
#  changed_when: "'SAPCAR: processing archive' in sap_swpm_extractswpm.stdout"
