---
# Ansible Playbook for executing sap_swpm Ansible in "Default Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true

  tasks:
  - set_fact:
      ip_list_short: "{{ ip_list | replace('[','') | replace(']','') }}"
      hostname_list_short: "{{ hostname_list | replace('[','') | replace(']','') }}"
  - set_fact:
      ip_array: "{{ ip_list_short.split(',') }}"
      hostname_array: "{{ hostname_list_short.split(',') }}"

  - name: SAP SWPM NW GL Preinstall - Update '/etc/hosts' for connected hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ ip_array[index] }}\t{{ hostname_array[index]}}.{{ ansible_domain }}\t{{ hostname_array[index]}}"
    loop: "{{ hostname_array  }}"
    loop_control:
      index_var: index
