---
- name: Ansible Play for executing preconfiguration activities for SAP HANA to all hosts in Ansible Inventory
  hosts: all
  become: true
  vars:
    sap_general_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_fail_if_reboot_required: no
    sap_hana_preconfigure_update: yes
    sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured: no
  roles:
    - { role: sap_general_preconfigure }
    - { role: sap_hana_preconfigure }
    - { role: sap_netweaver_preconfigure }
