---
# Ansible Playbook for executing sap_swpm Ansible in "Default Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true

  vars:
    sap_swpm_ansible_role_mode: default

  tasks:

    - name: Import variables for sap_swpm Ansible Role (Default Mode)
      ansible.builtin.include_vars:
#        file: ./sample-variables-sap-swpm-default-mode-bw4hana-onehost-install.yml
#        file: ./sample-variables-sap-swpm-default-mode-s4hana-distributed-ascs-install
#        file: ./sample-variables-sap-swpm-default-mode-s4hana-distributed-dbload-install
#        file: ./sample-variables-sap-swpm-default-mode-s4hana-distributed-ers-install
#        file: ./sample-variables-sap-swpm-default-mode-s4hana-distributed-pas-install
        file: ./variables-sap-swpm-default-mode-s4hana-onehost-install.yml
#        file: ./sample-variables-sap-swpm-default-mode-s4hana-onehost-restore.yml
#        file: ./sample-variables-sap-swpm-default-mode-solman-hana-abap-onehost-install.yml
#        file: ./sample-variables-sap-swpm-default-mode-solman-hana-java-onehost-install.yml
#        file: ./sample-variables-sap-swpm-default-mode-system-rename.yml
#        file: ./sample-variables-sap-swpm-default-mode-webdisp-standalone-install.yml

          #    - name: Execute Ansible Role sap_install_media_detect
          #      ansible.builtin.include_role:
        #        name: { role: community.sap_install.sap_install_media_detect }
        #        name: { role: sap_install_media_detect }
    - debug:
        msg: "SWPM: {{ sap_swpm_sapinst_path }}\n HANA system PW: {{sap_swpm_db_system_password}} \n SWPM master PW {{sap_swpm_master_password }} \n 
        sap_install_media_detect_source_directory: {{ sap_install_media_detect_source_directory}} \n CAtalog ID: {{ sap_swpm_product_catalog_id }} \n SAP APP SID: {{sap_swpm_sid}}\n ASCS {{ sap_swpm_ascs_instance_nr }} \n 
        HANA Host {{ sap_swpm_db_host}}\ \n pas instance number {{ sap_swpm_pas_instance_nr}} \n SAP HANA SID {{ sap_hana_install_sid }} \n SAP HANA Nr {{ sap_swpm_db_instance_nr }} \n "
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: { role: sap_swpm }
