---
# Ansible Playbook for executing sap_swpm Ansible in "Default Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true



  tasks:
  - debug:
      msg: "Ansible FQDN: {{ ansible_fqdn }}, Ansible hostname: {{ ansible_hostname }}"

