---
# Ansible Playbook for executing sap_swpm Ansible in "Default Mode"

- name: Ansible Play for executing SAP SWPM to all hosts in Ansible Inventory
  hosts: all
  become: true



  tasks:
  - debug:
      msg: "Ansible FQDN: {{ ansible_domain }}, Ansible hostname: {{ ansible_hostname }}"
  - set_fact:
      sap_swpm_fqdn: "{{ ansible_domain }}"
##
#  - name: Get IP adress from SAP HANA host
#    set_fact:
#      sap_hana_host_ip: "{{  ansible_default_ipv4.address }}"
#    delegate_to: "{{ sap_swpm_db_host }}"

#  - name: Set virtual hana hostname in /etc/hosts
#    lineinfile:
#      path: /etc/hosts
#      line: '{{  sap_hana_host_ip }}        {{ sap_swpm_db_host }}.{{ ansible_domain }}  {{ sap_swpm_db_host }}'
#      owner: root
#      group: root
#      mode: 0644

# Update etc hosts for NW
- debug:
    msg: "Debugging fqdn: {{ sap_swpm_fqdn }}"
  
- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' is not configured for NW due to missing 'sap_swpm_fqdn'
  ansible.builtin.debug:
    msg: "WARN: Not configuring NW entries in '/etc/hosts' because 'sap_swpm_fqdn' is not defined!"
  when:
    (sap_swpm_fqdn | type_debug == 'NoneType') or
    (sap_swpm_fqdn | length == 0)

# Update etc hosts for HANA

- name: SAP SWPM Pre Install - Update '/etc/hosts' for NW
  when:
    - "sap_swpm_fqdn | type_debug != 'NoneType'"
    - "sap_swpm_fqdn | length > 0"
  block:
   
    - name: SAP SWPM Pre Install - Deduplicate values from '/etc/hosts'
      ansible.builtin.lineinfile:
        path: /etc/hosts
        create: false
        regexp: (?i)^\s*{{ ansible_default_ipv4.address | d(ansible_all_ipv4_addresses[0]) }}\s+
        state: absent

# Reason for noqa: 1. Tabs can increase readability;
#                  2. Tabs are allowed for /etc/hosts
    - name: SAP SWPM Pre Install - Update '/etc/hosts' with NW entry # noqa no-tabs
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address | d(ansible_all_ipv4_addresses[0]) }}\t{{ ansible_hostname }}.{{ sap_swpm_fqdn }}\t{{ ansible_hostname }}"

- name: Get IP adress from SAP HANA host
  set_fact:
    sap_swpm_db_ip: "{{  ansible_default_ipv4.address }}"
  delegate_to: "{{ sap_swpm_db_host }}"
  when:  
    - sap_swpm_db_host != ansible_hostname
    - (sap_swpm_db_ip | type_debug == 'NoneType') or
      (sap_swpm_db_ip | length == 0)
     

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' is not configured for HANA due to missing 'sap_swpm_db_ip'
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_ip' is not defined!"
  when:
    (sap_swpm_db_ip | type_debug == 'NoneType') or
    (sap_swpm_db_ip | length == 0)

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' is not configured for HANA due to missing 'sap_swpm_db_host'
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_host' is not defined!"
  when:
    (sap_swpm_db_host | type_debug == 'NoneType') or
    (sap_swpm_db_host | length == 0)

- name: SAP SWPM Pre Install - Display warning message if '/etc/hosts' is not configured for HANA because 'sap_swpm_db_host' is the current host
  ansible.builtin.debug:
    msg: "WARN: Not configuring HANA entries in '/etc/hosts' because 'sap_swpm_db_host' is the current host!"
  when: sap_swpm_db_host == ansible_hostname

- name: SAP SWPM Pre Install - Update '/etc/hosts' for HANA
  when:
    - "sap_swpm_db_ip | type_debug != 'NoneType'"
    - "sap_swpm_db_ip | length > 0"
    - "sap_swpm_db_host | type_debug != 'NoneType'"
    - "sap_swpm_db_host | length > 0"
    - "sap_swpm_db_host != ansible_hostname"
  block:

    - name: SAP SWPM Pre Install - Deduplicate values from '/etc/hosts'
      ansible.builtin.lineinfile:
        path: /etc/hosts
        create: false
        regexp: (?i)^\s*{{ sap_swpm_db_ip }}\s+
        state: absent

# Reason for noqa: 1. Tabs can increase readability;
#                  2. Tabs are allowed for /etc/hosts
    - name: SAP SWPM Pre Install - Update '/etc/hosts' with HANA entry # noqa no-tabs
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ sap_swpm_db_ip }}\t{{ sap_swpm_db_host }}.{{ sap_swpm_fqdn }}\t{{ sap_swpm_db_host }}"
